### ISSUE TITLE
Dark/ Light Mode Toggle

### ISSUE THREAD

**Issue by aadityaa29** [aslams2020/Stark-Tech-Portfolio#160]
Hey! @aslams2020 ,
Add a toggle option into your nav-bar so that you can change in light mode and dark mode as well.
I would love to work on it.

![image](https://github.com/user-attachments/assets/bb245cc3-9cc1-4b72-9d9c-e0b3e59350a0)

**Comment by aditya07389** [comment]
# Hey @aslams2020 , 
I noticed that this issue has already been raised, and since it hasn't been assigned to anyone yet, I would like to work on it. I can add a dark mode and light mode toggle button similar to the one below.

Please assign this issue to me.

P.S.: Kindly add the labels `gssoc extended` and `hacktoberfest`.


![dark-mode-and-light-mode-toggle-buttons-vector](https://github.com/user-attachments/assets/01846d18-44f7-4cfc-a39d-6aa6c85fc2bf)

**Comment by vinay7376** [comment]
I can do this, please give this work to me

**Comment by vikassahu1** [comment]
Hello, I want to work on this issue please assign me this work.
Thank You!

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @aslams2020
