### ISSUE TITLE
A page for Ironman merchandise

### ISSUE THREAD

**Issue by ishakatiyar06** [aslams2020/Stark-Tech-Portfolio#317]
I'll create different cards for merchandise such as t-shirts, miniature, keychains,,etc. where user will be redirected to commercial website links and can purchase items.

**Comment by aslams2020** [comment]
I think instead of redirecting users to original commercial links.
Please make a page of merchandise with buy now , add to card option and a price tag on it. Along with its images.

Add the link to merchandise page in the footer of all the pages. 
replace "Franchise" with "Buy Merchandise"

![image](https://github.com/user-attachments/assets/15ef26e9-6d63-428a-bf8d-2ad3943ff2d3)

**Comment by aslams2020** [comment]
Level will be assigned based on the work. go ahead

**Comment by ishakatiyar06** [comment]
Yeah, sure.
